language: php
sudo: false
php:
- '5.6'
branches:
  only:
  - master
install:
- nvm install 4.2
- npm install
after_success:
- npm run build
- bash ./bin/deploy.sh
env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=masa.03191996@gmail.com
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=masa.03191996@gmail.com
    - secure: XsHfGtj6+1bFOdG+1LLm82RwJ5k22pCFvFam+0VrAjB759JBHbz1yode8x2bpgWX3qM1HDygNrEpsEieutkKV3j0QreRLtWQCbW26b23vqI+MKE6/7l6yIntab5nYZ6Cfg2Qb2CejLQcU8ffYuSo9KdvswhcmwS0GMeD6wjHHa/RwGJ5+MCTvEDHjYMLNq6Qu8fqjSmRO3EjN6MvHCmRzIFyXpmXUCIil5IkmwfceWmx0AuwIiGhbjx8vwUH1vmZUGCYT7O4UC4pnLzRRyLB15FgYFwqCydGYU4sAxO3rQN5z6TsvxxWwtkcpZYb4Z9jZ/gCqj8w8cAmsTLcs22z1eRBuszk1PlLt5ncU8jkSMN9xS/eCKreVfyhkFShzxfCScQ6JjDFM2U/u1QaZ9R3L2+HBJHZHn36552COIdg3itZZHUJiYu1m5mwScvHQ9IfkAg1NaYNN5SrgiThDQfRnuaVRnQPvlgUgd4YFNbirkx/Y10iv61BJAgPwOk34jR1amvLxmFNNEKXuLypb90PJ4ngZEp+Lr5HbL/B3k/Eev41I1WZ+Ycg10EHp94H5ei46HEk/cGpnJhMrrt1IuVQt3S/PeuAdDzETnDhsU4KwfqL6B7dMCj3M/gj/J5SBPgQPCkoY0rzxMR69B/1E6qJu7KEnRKI3MEPSwWkaZ6KUME=
