version: "3"
services:

  node:
    build:
      context: ./
      dockerfile: docker/Dockerfile-TR
    container_name: ssa_task_runner
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

  wordpress:
    build:
      context: ./docker
      dockerfile: Dockerfile-wp
    container_name: ssa
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./:/var/www/html/wp-content/themes/xeory_base_child
      - plugins:/var/www/html/wp-content/plugins

  mysql:
    image: mysql:5.7
    container_name: ssa_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  plugins:
  node_modules: